nome = input("Qual seu nome? ")
print('Formatando Posições da variável no print')
print('-'*50)
print("Prazer em te conhecer {:20}!".format(nome))
print('-'*50)
print("Prazer em te conhecer {:<20}!".format(nome))
print('-'*50)
print("Prazer em te conhecer {:>20}!".format(nome))
print('-'*50)
print("Prazer em te conhecer {:^20}!".format(nome))
print('-'*50)
print("Prazer em te conhecer {:=^20}!".format(nome))
print('-'*50)